### ISSUE TITLE
Our Story Page - update copy

### ISSUE THREAD

**Issue by peak9ine** [CKMKDigital/Zukes#86] opened 2016-06-15 13:29 UTC
Make sure to pull latest copy for Values section before launch

**Comment by lizbethsteele** [comment] 2016-06-15 15:53
Waiting for copy from Paula / Georganne.

**Comment by sarahbrule** [comment] 2016-06-21 15:32
@lizbethsteele  - We have received updated copy. I will attach the word doc via email.

**Comment by sarahbrule** [comment] 2016-06-21 15:37
I believe this is a duplicate of issue 75?

**Closed as completed** 2016-06-21 21:23 UTC
Labels: cms copy
